"""initial migration

Revision ID: 2db6d6adf16f
Revises: None
Create Date: 2014-10-19 14:50:27.142928

"""

# revision identifiers, used by Alembic.
revision = '2db6d6adf16f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
